name: habits-tracker

services:

  postgres:
    image: postgres:17.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  fastapi_app:
    build:
      context: fastapi_app/.
    environment:
      DB_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_INTERNAL_PORT}/${DB_NAME}"
      SECRET_KEY: ${FASTAPI_SECRET_KEY}
    ports:
      - "${FASTAPI_PORT}:8000"
    depends_on:
      - postgres
    command: >
      uvicorn src.fastapi_app.main:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - action: rebuild
          path: ./fastapi_app/pyproject.toml
          target: /app/pyproject.toml
        - action: sync
          path: ./fastapi_app/src/
          target: /app/src/
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  pg_data:
  redis_data:

networks:
  backend: