name: habits-tracker


x-common: &common-env
  env_file: .env


services:

  postgres:
    <<:
      - *common-env
    image: postgres:17.0
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSW}
      POSTGRES_DB: ${DB__NAME}
    ports:
      - "${DB__EXTERNAL_PORT}:${DB__PORT}"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend


  fastapi_app:
    <<:
      - *common-env
    build:
      dockerfile: ./docker/fastapi_app/Dockerfile
      context: .
    environment:
      DB__HOST: postgres
    ports:
      - "${APP__EXTERNAL_PORT}:${APP__PORT}"
    depends_on:
      - postgres
    command: >
      uv run uvicorn --app-dir=/usr/app/src/ fastapi_app.main:app --host 0.0.0.0 --port ${APP__PORT}
    develop:
      watch:
        - action: sync+restart
          path: fastapi-app/src/
          target: /usr/app/src/
#    restart: unless-stopped
    networks:
      - backend



  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend


volumes:
  pg_data:
  redis_data:


networks:
  backend: